#!/usr/bin/env python3
"""
Generate browsable index READMEs for the organised output folders:
  pdf/README.md  — links straight to every compiled PDF, grouped by concept
  tex/README.md  — links to every LaTeX source, grouped by concept

Keeps them in sync with build.py's REG + FOLDER. Run after a build.
"""
from pathlib import Path
import pypdfium2 as pdfium
from build import REG, FOLDER, TEXDIR, PDFDIR, folder_of

# display name + order for the concept folders
FOLDER_META = [
    ("_collection",   "📚 Collection (cover, catalogue & merged book)"),
    ("foundations",   "🧱 Foundations"),
    ("systems",       "⚙️ Systems"),
    ("system-design", "🏗️ System Design"),
    ("data",          "🗄️ Data"),
    ("infrastructure","☁️ Infrastructure & Ops"),
    ("dev-practices", "🔧 Dev Practices"),
    ("dsa",           "🧩 DSA"),
    ("ai-ml",         "🤖 AI / ML"),
    ("behavioral",    "💬 Behavioral"),
]
TITLE = {key: title.replace("\\&", "&") for key, _, title, *_ in REG}

def pages(p: Path) -> str:
    try:
        return str(len(pdfium.PdfDocument(str(p))))
    except Exception:
        return "—"

def keys_in(folder):
    return [k for k, *_ in REG if folder_of(k) == folder]

def gen(kind):  # kind = "pdf" or "tex"
    ext = ".pdf" if kind == "pdf" else ".tex"
    root = PDFDIR if kind == "pdf" else TEXDIR
    out = [f"# {'📄 Compiled PDFs' if kind=='pdf' else '📝 LaTeX Sources'}",
           "",
           ("Click any edition to open it. Generated by `make_readmes.py` — grouped by "
            "concept folder (see `../build.py` `FOLDER`)."),
           ""]
    # collection first (special files)
    cdir = root / "_collection"
    if kind == "pdf" and cdir.exists():
        out += ["## 📚 The Whole Library", "",
                "| File | What it is | Pages |", "|------|------------|------:|"]
        for fn, desc in [("Complete-Collection.pdf", "**Every edition in one bookmarked book**"),
                         ("00-Collection-Index.pdf", "Cover + catalogue of all editions")]:
            p = cdir / fn
            if p.exists():
                out.append(f"| [`{fn}`](_collection/{fn}) | {desc} | {pages(p)} |")
        out.append("")

    total = 0
    for folder, label in FOLDER_META:
        ks = keys_in(folder)
        rows = []
        for k in ks:
            f = root / folder / f"{k}{ext}"
            if not f.exists():
                continue
            if kind == "pdf":
                rows.append(f"| {TITLE.get(k,k)} | [`{k}.pdf`]({folder}/{k}.pdf) | {pages(f)} |")
            else:
                rows.append(f"| {TITLE.get(k,k)} | [`{k}.tex`]({folder}/{k}.tex) |")
        if not rows:
            continue
        total += len(rows)
        out.append(f"## {label}")
        out.append("")
        out.append("| Edition | File | Pages |" if kind == "pdf" else "| Edition | File |")
        out.append("|---------|------|------:|" if kind == "pdf" else "|---------|------|")
        out += rows
        out.append("")
    out.append(f"---\n\n*{total} editions. Rebuild with `python3 build.py` (then `make_index.py`, "
               f"`make_readmes.py`).*")
    (root / "README.md").write_text("\n".join(out) + "\n")
    print(f"  ok  {root.name}/README.md  ({total} editions linked)")

if __name__ == "__main__":
    gen("pdf")
    gen("tex")
